### PR TITLE
[SERF-472] Add CORS settings to server

### PR DESCRIPTION
**Pull request by Neurostep**
## Description

In this PR we extend the Server config to include CORS settings. CORS is disabled by default.
CORS settings aim to attach per route

```go
      Setting struct {
		Path string `mapstructure:"path"`

		AllowedOrigins   []string `mapstructure:"allowed_origins"`
		AllowedMethods   []string `mapstructure:"allowed_methods"`
		AllowedHeaders   []string `mapstructure:"allowed_headers"`
		ExposedHeaders   []string `mapstructure:"exposed_headers"`
		AllowCredentials bool     `mapstructure:"allow_credentials"`

		MaxAge int `mapstructure:"max_age"`

		OptionsPassthrough bool `mapstructure:"options_passthrough"`
	}
```
The `Route` is matched by the `Path` field (only the exact match is currently supported). There is a special `Path` value `"*"` which applies to all existing routes

Go SDK abstracts the way to work with CORS into the middleware. Currently, under the hood it uses [cors](https://github.com/rs/cors) library that provides full support of the [CORS protocol](https://fetch.spec.whatwg.org/#http-cors-protocol)

## Checklist

- [x] Prefixed the PR title with the JIRA ticket code 
- [x] Performed simple, atomic commits with [good commit messages][commit messages]
- [x] Verified that the commit history is linear and commits are squashed as necessary
- [ ] Thoroughly tested the changes in `development` and/or `staging`
- [ ] Updated the `README.md` as necessary

## Related links

* [SERF-472](https://scribdjira.atlassian.net/browse/SERF-472)
* https://github.com/rs/cors
* https://github.com/scribd/web-analytics-ingestion/pull/3
* https://fetch.spec.whatwg.org/#http-cors-protocol

[commit messages]: https://chris.beams.io/posts/git-commit/

### CODE REVIEW

**Review by fotos — DISMISSED** [review]
:+1: LGTM 👏

**Review by fotos — DISMISSED** [review]
:+1: LGTM 🚀

**Review by fteem — DISMISSED** [review]
LGTM 👌

**Review by fteem — DISMISSED** [review]
LGTM

**Review by fotos — DISMISSED** [review]
:+1: LGTM 🚀 

Left a few comments for the README.

**Review by fotos — DISMISSED** [review]
:+1: LGTM 🚀

**Review by fotos — APPROVED** [review]
:+1: LGTM 🚀

**Pull request merged**
